package gui;

import data.Dictionary;
import java.awt.Color;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.Locale;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    Locale lo;
    Dictionary d;
    int flag = 1;//1: V_E; 2: E_V
    LinkedList<String> listVocab = null;
    public MainFrame() {
        initComponents();
        loadData();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtWtsl = new javax.swing.JTextField();
        txtWord = new javax.swing.JTextField();
        btnTsl = new javax.swing.JButton();
        rdEV = new javax.swing.JRadioButton();
        rdVE = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaSnm = new javax.swing.JTextArea();
        btnAddWord = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dictionary");
        setBackground(new java.awt.Color(255, 102, 102));

        btnTsl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTsl.setText("Translate");
        btnTsl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTslActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdEV);
        rdEV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdEV.setSelected(true);
        rdEV.setText("EN_VN");
        rdEV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdEVActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdVE);
        rdVE.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdVE.setText("VN_EN");
        rdVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdVEActionPerformed(evt);
            }
        });

        txtAreaSnm.setColumns(20);
        txtAreaSnm.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtAreaSnm.setRows(5);
        txtAreaSnm.setEnabled(false);
        jScrollPane1.setViewportView(txtAreaSnm);

        btnAddWord.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddWord.setText("Add Word");
        btnAddWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddWordActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DICTIONARY");

        jLabel2.setText("*EN_VN: translate English to Vietnamese");

        jLabel3.setText("*VN_EN: translate VietNamese to English");

        jLabel4.setText("*Click again on one of circle buttons to retype");

        jButton1.setText("How to add new word ? ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(243, 243, 243))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addComponent(btnAddWord, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtWord, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rdVE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rdEV, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(73, 73, 73)
                                        .addComponent(txtWtsl, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(128, 128, 128)
                                        .addComponent(btnTsl))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(jButton1)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtWtsl, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtWord, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTsl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddWord, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdEV, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdVE, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdEVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdEVActionPerformed
        rdEV.setSelected(true);
        flag = 0;
        txtWord.setText("");
        txtWtsl.setText("");
        txtAreaSnm.setText("");      
    }//GEN-LAST:event_rdEVActionPerformed

    private void btnTslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTslActionPerformed
        String inputWord = txtWord.getText();
        //LinkedList<String> listVocab = null;
        if(inputWord.isEmpty()){
            return;
        }
        if(rdEV.isSelected()){
            listVocab = d.translateEnToVi(inputWord);
            if(listVocab != null){
                txtWtsl.setText(listVocab.get(0));
                txtAreaSnm.setText(listVocab.toString());
                Iterator i = listVocab.iterator();
                while (i.hasNext()) {
                    txtAreaSnm.setToolTipText((String) i.next());
                }
            }else{
                JOptionPane.showMessageDialog(null, "This word is not in the dictionary.");
            }           
        }else{
            listVocab = d.translateViToEn(inputWord);
            if(listVocab != null){
                txtWtsl.setText(listVocab.get(0));
                txtAreaSnm.setText(listVocab.toString());
                Iterator i = listVocab.iterator();
                while (i.hasNext()) {
                    txtAreaSnm.setToolTipText((String) i.next());
                }
            }else{
                JOptionPane.showMessageDialog(null, "Từ này không có trong từ điển.");
            }      
        }
        
    }//GEN-LAST:event_btnTslActionPerformed

    private void rdVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdVEActionPerformed
        rdVE.setSelected(true);
        flag = 1;
        txtWord.setText("");
        txtWtsl.setText("");
        txtAreaSnm.setText("");
    }//GEN-LAST:event_rdVEActionPerformed

    private void btnAddWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddWordActionPerformed
        String newWord = txtWord.getText();
           String mean = txtWtsl.getText();
           
        if(rdEV.isSelected()){           
           if(!newWord.isEmpty() && !mean.isEmpty()){
               if(d.addEnWord(newWord, mean)){
                   d.addEVToVn_En(newWord, mean);
                   loadData();
                   JOptionPane.showMessageDialog(null, "Done!!!");
               }
           }
        }else{
           if(!newWord.isEmpty() && !mean.isEmpty()){
               if(d.addVnWord(newWord, mean)){
                   d.addVEToEn_Vn(newWord, mean);
                   loadData();
                   JOptionPane.showMessageDialog(null, "Đã xong!!!");
               }else{
                   JOptionPane.showMessageDialog(null, "Từ này đã có trong từ điển.");
               }
           } 
        }
    }//GEN-LAST:event_btnAddWordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String msg = "1. Thêm từ mới: gõ vào ô textfield bên phải, nếu từ có nhiều hơn một nghĩa thì ngăn cách nhau bởi dấu ','.\n";
        String msg1 = "2. Thêm synonyms: gõ thêm vào đằng sau nghĩa đã dịch, ngăn cách nhau bằng dấu phẩy.\n";
        String msg2 = "*Sau khi thực hiện 1 hoặc 2, nhấn nút add word để hoàn thành thao tác.";
        JOptionPane.showMessageDialog(null, msg+msg1+msg2);
                
    }//GEN-LAST:event_jButton1ActionPerformed
    void loadData(){
        d = new Dictionary("en_vn.txt", "vn_en.txt"); 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrame m = new MainFrame();
                m.setVisible(true);
                m.setLocationRelativeTo(null);
                m.getContentPane().setBackground(new Color(255, 102, 102));
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddWord;
    private javax.swing.JButton btnTsl;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdEV;
    private javax.swing.JRadioButton rdVE;
    private javax.swing.JTextArea txtAreaSnm;
    private javax.swing.JTextField txtWord;
    private javax.swing.JTextField txtWtsl;
    // End of variables declaration//GEN-END:variables
}
